# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Env-Bash
version:      0.00_02
version_from: lib/Env/Bash.pm
installdirs:  site
requires:
    Test::More:                    0.5

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
